Repository cidade-integra/cidade-integra-frontend, pull requests merged in 2025-04, with the labels that each got.

#22 Correcao/header
  frontend/src/components/NavLinks.jsx
Labels: bug, enhancement

#23 Develop
  frontend/src/components/NavLinks.jsx
Labels: bug, enhancement

#24 Autenticação Firebase
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/FormularioCriarConta.jsx
  frontend/src/hooks/UseAuthentication.jsx
  frontend/src/services/FirebaseConfig.jsx
Labels: enhancement

#25 Develop
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/FormularioCriarConta.jsx
  frontend/src/hooks/UseAuthentication.jsx
  frontend/src/services/FirebaseConfig.jsx
Labels: enhancement

#26 Implementacao/login firebase
  frontend/package-lock.json
  frontend/src/components/FormularioCriarConta.jsx
  frontend/src/components/FormularioLogin.jsx
  frontend/src/firebase/config.jsx
  frontend/src/services/FirebaseConfig.jsx
Labels: enhancement

#27 Develop
  frontend/package-lock.json
  frontend/src/components/FormularioCriarConta.jsx
  frontend/src/components/FormularioLogin.jsx
  frontend/src/firebase/config.jsx
  frontend/src/services/FirebaseConfig.jsx
Labels: enhancement

#28 Implementacao/login google firebase
  frontend/src/components/FormularioLogin.jsx
  frontend/src/firebase/config.jsx
Labels: enhancement

#29 Develop
  frontend/src/components/FormularioLogin.jsx
  frontend/src/firebase/config.jsx
Labels: enhancement

#32 feat: adicionar componente AvatarSuspenso para gerenciamento de perfi…
  frontend/src/components/AvatarSuspenso.jsx
  frontend/src/components/FormularioLogin.jsx
  frontend/src/components/NavLinks.jsx
Labels: enhancement

#34 Implementacao/perfil
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CriarConta/FormularioCriarConta.jsx
  frontend/src/components/Entrar/FormularioLogin.jsx
  frontend/src/components/EsqueciSenha/FormularioEsqueciSenha.jsx
  frontend/src/components/PaginaInicial/BemVindo.jsx
  frontend/src/components/PaginaInicial/NossaEquipe.jsx
  frontend/src/components/PaginaInicial/NossosValores.jsx
  frontend/src/components/Perfil/UserInfoCard.jsx
  frontend/src/components/Perfil/UserStatsCard.jsx
  frontend/src/components/layout/AvatarSuspenso.jsx
  frontend/src/components/layout/Footer.jsx
  frontend/src/components/layout/Header.jsx
  frontend/src/components/layout/Layout.jsx
  frontend/src/components/layout/NavLinks.jsx
  frontend/src/pages/CriarConta.jsx
  frontend/src/pages/Denuncia.jsx
  frontend/src/pages/Duvidas.jsx
  frontend/src/pages/Entrar.jsx
  frontend/src/pages/EsqueciSenha.jsx
  frontend/src/pages/PaginaInicial.jsx
  frontend/src/pages/Perfil.jsx
  frontend/src/routes/AppRoutes.jsx
  frontend/src/routes/ProtectedRoute.jsx
Labels: enhancement

#37 correção e melhorias
  frontend/src/components/CriarConta/FormularioCriarConta.jsx
  frontend/src/components/layout/AvatarSuspenso.jsx
Labels: bug

#52 firebase deploy
  frontend/.firebase/hosting.ZGlzdA.cache
  frontend/dist/assets/favicon-CmXYP4bq.ico
  frontend/dist/assets/index-B0hcwYUl.js
  frontend/dist/assets/index-BOZcSGSn.css
  frontend/dist/index.html
  frontend/src/components/PaginaInicial/BemVindo.jsx
  frontend/src/components/PaginaInicial/NossaEquipe.jsx
  frontend/src/components/PaginaInicial/NossosValores.jsx
  frontend/src/components/layout/Footer.jsx
  frontend/src/components/layout/Header.jsx
Labels: enhancement
