Repository cidade-integra/cidade-integra-frontend, pull requests merged in 2025-05, with the labels that each got.

#59 Correções de Responsividade
  frontend/src/components/home/HeroSection.jsx
  frontend/src/components/layout/DesktopMenu.jsx
  frontend/src/components/layout/MobileMenu.jsx
  frontend/src/components/layout/Navbar.jsx
Labels: bug, enhancement

#60 Refatorações de código, Desempenho e SEO
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/hero-foto.avif
  frontend/public/robots.txt
  frontend/public/sitemap.xml
  frontend/src/components/authentication/GoogleLoginButton.jsx
  frontend/src/components/authentication/LoginForm.jsx
  frontend/src/components/authentication/RegisterForm.jsx
  frontend/src/components/authentication/shared/AuthNotice.jsx
  frontend/src/components/home/HeroSection.jsx
  frontend/src/components/layout/Navbar.jsx
  frontend/src/components/perfil/EditarPerfilForm.jsx
  frontend/src/components/perfil/EstatisticasCard.jsx
  frontend/src/components/perfil/MinhasDenuncias.jsx
  frontend/src/components/perfil/PerfilHeader.jsx
  frontend/src/components/perfil/PerfilUsuarioCard.jsx
  frontend/src/components/ui/alert-dialog.jsx
  frontend/src/components/ui/dialog.jsx
  frontend/src/data/equipe.jsx
  frontend/src/hooks/UseAuthentication.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/PerfilUsuarioPage.jsx
  frontend/src/pages/RecuperarSenhaPage.jsx
  frontend/src/pages/SobrePage.jsx
  frontend/src/routes/AppRoutes.jsx
Labels: enhancement

#97 docs: melhorei o readme.md
  README.md
Labels: enhancement

#98 actions: criei codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#106 docs: Atualização do Nome do Projeto
  README.md
Labels: test

#113 Adição de botão para desativação de conta com modal de confirmação
  frontend/src/components/layout/Footer.jsx
  frontend/src/components/perfil/ConfirmDeactivateDialog.jsx
  frontend/src/hooks/useDeleteAccount.jsx
  frontend/src/pages/PerfilUsuarioPage.jsx
Labels: enhancement

#115 Correções de Comportamento Inesperados
  frontend/src/components/layout/MobileMenu.jsx
  frontend/src/components/layout/Navbar.jsx
  frontend/src/components/perfil/EditarPerfilForm.jsx
Labels: bug
