Repository cidade-integra/cidade-integra-frontend, pull requests merged in 2025-06, with the labels that each got.

#119 Develop - Implementação de upload
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/denunciaForm/DenunciaForm.jsx
  frontend/src/components/denunciaForm/ImageUpload.jsx
  frontend/src/components/denuncias/DenunciaCard.jsx
  frontend/src/hooks/useReport.jsx
  frontend/src/hooks/useUploadImageReport.jsx
  frontend/src/supabase/config.jsx
  package-lock.json
  package.json
Labels: enhancement

#225 [EXTRA - 34 pontos] Criar chatbot simples com respostas automáticas na home
  frontend/src/components/home/Chatbot.jsx
  frontend/src/pages/Index.jsx
Labels: enhancement, avaliacao-dw3

#233 [21 pontos] Criar página com histórico de denúncias com paginação e busca
  frontend/src/components/denuncias/DenunciasList.jsx
  frontend/src/hooks/useReport.jsx
Labels: enhancement, avaliacao-dw3

#242 [3 pontos] Ajustar contraste dos botões principais para acessibilidade
  frontend/src/components/ui/button.jsx
  frontend/src/index.css
Labels: enhancement, avaliacao-dw3

#243 Primeira Entrega para Produção (`develop` → `main`)
  frontend/public/article-cidade-integra.pdf
  frontend/src/components/admin/denuncias/DenunciasSearch.jsx
  frontend/src/components/admin/denuncias/ExportCSV.jsx
  frontend/src/components/authentication/RegisterForm.jsx
  frontend/src/components/denuncias/CardDenuncia.jsx
  frontend/src/components/denuncias/DenunciasList.jsx
  frontend/src/components/home/Chatbot.jsx
  frontend/src/components/home/HowItWorksSection.jsx
  frontend/src/components/layout/Footer.jsx
  frontend/src/components/perfil/EstatisticasCard.jsx
  frontend/src/components/perfil/MinhasDenuncias.jsx
  frontend/src/components/sobre/StudentCard.jsx
  frontend/src/data/faqData.jsx
  frontend/src/hooks/useReport.jsx
  frontend/src/pages/AdminPage.jsx
  frontend/src/pages/Index.jsx
  frontend/src/pages/SobrePage.jsx
  frontend/src/routes/AppRoutes.jsx
  frontend/src/utils/ScrollToTop.jsx
Labels: enhancement

#237 [21 pontos] Criar sistema de favoritos ou “Minhas denúncias salvas"
  frontend/src/components/denuncias/CardDenuncia.jsx
  frontend/src/components/faq/ContactSection.jsx
  frontend/src/components/faq/FAQCategory.jsx
  frontend/src/components/faq/FAQHeader.jsx
  frontend/src/components/faq/FAQPage.jsx
  frontend/src/components/faq/FAQSection.jsx
  frontend/src/components/perfil/MinhasDenuncias.jsx
  frontend/src/data/equipe.jsx
  frontend/src/data/faqData.jsx
  frontend/src/index.css
  frontend/src/pages/DenunciaDetalhes.jsx
  frontend/src/utils/saveReport.jsx
  package-lock.json
Labels: enhancement, avaliacao-dw3

#244 [21 pontos] Implementar mapa estático com marcadores de denúncias geolocalizadas
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/denuncias/MapaEstatico.jsx
  frontend/src/components/ui/aspect-ratio.jsx
  frontend/src/pages/DenunciaDetalhes.jsx
Labels: enhancement, avaliacao-dw3

#245 Entrega para Produção (`develop` → `main`)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/denuncias/CardDenuncia.jsx
  frontend/src/components/denuncias/MapaEstatico.jsx
  frontend/src/components/faq/ContactSection.jsx
  frontend/src/components/faq/FAQCategory.jsx
  frontend/src/components/faq/FAQHeader.jsx
  frontend/src/components/faq/FAQNavigation.jsx
  frontend/src/components/faq/FAQPage.jsx
  frontend/src/components/faq/FAQSection.jsx
  frontend/src/components/perfil/MinhasDenuncias.jsx
  frontend/src/components/ui/aspect-ratio.jsx
  frontend/src/data/equipe.jsx
  frontend/src/data/faqData.jsx
  frontend/src/hooks/useScrollSpy.jsx
  frontend/src/index.css
  frontend/src/pages/DenunciaDetalhes.jsx
  frontend/src/pages/FAQPage.jsx
  frontend/src/utils/saveReport.jsx
  package-lock.json
Labels: enhancement

#246 [8 pontos] Destacar visualmente a página ativa no menu de navegação
  frontend/src/components/layout/DesktopMenu.jsx
  frontend/src/components/layout/MobileMenu.jsx
Labels: enhancement, avaliacao-dw3

#247 [21 pontos] Implementar navegação por teclado e foco acessível
  frontend/src/App.jsx
  frontend/src/accessibility.css
  frontend/src/components/authentication/LoginForm.jsx
  frontend/src/components/layout/DesktopMenu.jsx
  frontend/src/components/layout/MobileMenu.jsx
  frontend/src/components/layout/Navbar.jsx
  frontend/src/components/ui/checkbox.jsx
  frontend/src/hooks/useAccessibility.jsx
  frontend/src/index.css
Labels: enhancement, avaliacao-dw3

#252 Desenvolver página institucional “Dúvidas Frequentes” com dados do Firestore
  frontend/src/App.jsx
  frontend/src/components/faq/FAQCategory.jsx
  frontend/src/components/faq/FAQPage.jsx
  frontend/src/components/faq/FAQSection.jsx
  frontend/src/components/layout/DesktopMenu.jsx
  frontend/src/components/layout/MobileMenu.jsx
  frontend/src/hooks/useFaq.jsx
  frontend/src/pages/Faq.jsx
  frontend/src/routes/AppRoutes.jsx
Labels: enhancement, avaliacao-dw3

#253 [5 pontos] Tornar os ícones da página "Sobre" semanticamente relevantes
  frontend/src/components/perfil/EstatisticasCard.jsx
  frontend/src/pages/PerfilUsuarioPage.jsx
  frontend/src/pages/SobrePage.jsx
Labels: enhancement, avaliacao-dw3

#255 [5 pontos] Tornar o botão “Editar Perfil” visualmente interativo
  frontend/src/components/perfil/PerfilUsuarioCard.jsx
Labels: enhancement, avaliacao-dw3

#256 [8 pontos] Diferenciar visualmente títulos clicáveis de não clicáveis
  frontend/src/components/faq/FAQSection.jsx
Labels: enhancement, avaliacao-dw3

#260 [34 pontos] Refatorar sistema de denúncias para permitir upload múltiplo de imagens
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/denunciaForm/DenunciaForm.jsx
  frontend/src/components/denunciaForm/ImageUpload.jsx
  frontend/src/components/denuncias/CardDenuncia.jsx
  frontend/src/components/denuncias/MapaEstatico.jsx
  frontend/src/components/ui/carousel.jsx
  frontend/src/hooks/useReport.jsx
  frontend/src/pages/DenunciaDetalhes.jsx
Labels: enhancement, avaliacao-dw3

#262 fix: ajuste na seção FAQ para responsividade
  frontend/src/components/faq/FAQSection.jsx
  frontend/src/pages/FAQPage.jsx
Labels: bug
